// flow-typed signature: d7105725bce8d47013cf4c502cf38ce5
// flow-typed version: <<STUB>>/css-selector-parser_v^1.3.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-selector-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-selector-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-selector-parser/lib/css-selector-parser' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-selector-parser/index' {
  declare module.exports: $Exports<'css-selector-parser'>;
}
declare module 'css-selector-parser/index.js' {
  declare module.exports: $Exports<'css-selector-parser'>;
}
declare module 'css-selector-parser/lib/css-selector-parser.js' {
  declare module.exports: $Exports<'css-selector-parser/lib/css-selector-parser'>;
}
