// flow-typed signature: 78de4fa03a935385d132968cb9baaa68
// flow-typed version: <<STUB>>/flow-bin_v^0.44.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-bin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-bin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-bin/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-bin/cli.js' {
  declare module.exports: $Exports<'flow-bin/cli'>;
}
declare module 'flow-bin/index' {
  declare module.exports: $Exports<'flow-bin'>;
}
declare module 'flow-bin/index.js' {
  declare module.exports: $Exports<'flow-bin'>;
}
