// flow-typed signature: c5e611157fd5f9de26a342469526a2e9
// flow-typed version: <<STUB>>/pretty-format_v^19.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pretty-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pretty-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pretty-format/build/index' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/AsymmetricMatcher' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/escapeHTML' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/ReactElement' {
  declare module.exports: any;
}

declare module 'pretty-format/build/plugins/ReactTestComponent' {
  declare module.exports: any;
}

declare module 'pretty-format/perf/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pretty-format/build/index.js' {
  declare module.exports: $Exports<'pretty-format/build/index'>;
}
declare module 'pretty-format/build/plugins/AsymmetricMatcher.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/AsymmetricMatcher'>;
}
declare module 'pretty-format/build/plugins/escapeHTML.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/escapeHTML'>;
}
declare module 'pretty-format/build/plugins/ReactElement.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/ReactElement'>;
}
declare module 'pretty-format/build/plugins/ReactTestComponent.js' {
  declare module.exports: $Exports<'pretty-format/build/plugins/ReactTestComponent'>;
}
declare module 'pretty-format/perf/test.js' {
  declare module.exports: $Exports<'pretty-format/perf/test'>;
}
