// flow-typed signature: d974d1e70280a110d80d6bfb9643e5dc
// flow-typed version: <<STUB>>/scalpel_v^2.1.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scalpel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scalpel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scalpel/dist/browser' {
  declare module.exports: any;
}

declare module 'scalpel/dist/createGenerator' {
  declare module.exports: any;
}

declare module 'scalpel/dist/createParser' {
  declare module.exports: any;
}

declare module 'scalpel/dist/grammar' {
  declare module.exports: any;
}

declare module 'scalpel/dist/index' {
  declare module.exports: any;
}

declare module 'scalpel/dist/types' {
  declare module.exports: any;
}

declare module 'scalpel/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scalpel/dist/browser.js' {
  declare module.exports: $Exports<'scalpel/dist/browser'>;
}
declare module 'scalpel/dist/createGenerator.js' {
  declare module.exports: $Exports<'scalpel/dist/createGenerator'>;
}
declare module 'scalpel/dist/createParser.js' {
  declare module.exports: $Exports<'scalpel/dist/createParser'>;
}
declare module 'scalpel/dist/grammar.js' {
  declare module.exports: $Exports<'scalpel/dist/grammar'>;
}
declare module 'scalpel/dist/index.js' {
  declare module.exports: $Exports<'scalpel/dist/index'>;
}
declare module 'scalpel/dist/types.js' {
  declare module.exports: $Exports<'scalpel/dist/types'>;
}
declare module 'scalpel/webpack.config.js' {
  declare module.exports: $Exports<'scalpel/webpack.config'>;
}
